### ISSUE TITLE
Enable conflict resolution (line by line) 

### ISSUE THREAD

**Issue by andreasmjg-xx** [todotxt/todo.txt-android#471] opened 2016-10-27 14:29 UTC
If files have been edited on both ends, then make an interface for conflict resolution in the doc. 

Perhaps show local version on the top, remote on the bottom, with check boxes next to each line. Then the user can check which line to keep in the post-conflict version. 

Doesn't need be fancy, all it requires is that user understands that "line checked will carry forward, all else will be deleted". 

For v1 of this feature, perhaps don't even check what lines are different. Just if text file is different (already done), then bring up check mark interface and user can click away to decide what lines to copy to the new file.

**Comment by evanp** [comment] 2018-03-16 17:40
I think this is a duplicate of #448 .

**Closed by evanp** 2018-03-16 17:40 UTC
Labels: enhancement, sync
